name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Here is the message in GitHub Actions"

      - uses: actions/checkout@v2

      - run: ls

      - name: Install dependencies
        run: npm install

      - name: Building
        run: |
          npm run build
